import json
from loguru import logger
from pydantic import ValidationError

from app.config import settings
from app.services.llm_provider import planning_endpoint
from app.schemas.edit_plan import LLMPlan, LLMPlanSegment
from app.models.edit_plan import EditSegmentAction


class PlanningError(Exception):
    pass


class PlanningService:
    """
    Generates a structured edit plan from scene + transcript data using a
    planning LLM (OpenAI-compatible endpoint).  Model and endpoint are
    configured entirely via env — works against Ollama, vLLM, or any OAI API.

    On validation failure the prompt is retried exactly once with the
    validation error appended.  A second failure raises PlanningError.
    """

    def _build_prompt(
        self,
        video_id: str,
        scenes: list,
        segments: list,
        timeline_events: list | None = None,
        previous_error: str | None = None,
    ) -> str:
        scenes_summary = [
            {
                "scene_id": str(sc.id),
                "scene_number": sc.scene_number,
                "start": sc.start_time,
                "end": sc.end_time,
                "description": sc.description or "",
                "visual_tags": sc.visual_tags or [],
                "quality_flags": sc.quality_flags or {},
            }
            for sc in scenes[:30]
        ]
        transcript_preview = [
            {"start": s.start_time, "end": s.end_time, "text": s.text}
            for s in segments[:40]
        ]
        threshold = settings.timeline_confidence_threshold
        eligible = [te for te in (timeline_events or []) if te.confidence >= threshold]
        filtered_out = len(timeline_events or []) - len(eligible)
        if filtered_out:
            logger.info(
                f"Planning prompt: filtered {filtered_out} low-confidence timeline events "
                f"(threshold={threshold}) for video {video_id}"
            )
        timeline_preview = [
            {
                "start": te.start_ts,
                "end": te.end_ts,
                "description": te.description,
                "tags": te.tags or [],
                "confidence": round(te.confidence, 2),
            }
            for te in eligible[:50]
        ]
        schema_desc = (
            '{"segments": [{"scene_id": "<uuid>", "action": "keep" | "cut", '
            '"reason": "<why>", "caption": "<text overlay>", "order": <int>}]}'
        )
        base = (
            f"You are a professional video editor. Given the scene analysis, "
            f"event timeline, and transcript for video {video_id}, produce a JSON edit plan.\n\n"
            f"Rules:\n"
            f"- Use the event timeline to understand what happens within each scene\n"
            f"- Keep scenes with rich content; cut static/silent/blurry scenes\n"
            f"- Assign a short punchy caption referencing the key event in each kept scene\n"
            f"- Order kept scenes by their original scene_number\n"
            f"- Respond with ONLY valid JSON matching: {schema_desc}\n\n"
            f"Scenes:\n{json.dumps(scenes_summary, indent=2)}\n\n"
        )
        if timeline_preview:
            base += f"Event Timeline:\n{json.dumps(timeline_preview, indent=2)}\n\n"
        base += f"Transcript (first 40 segments):\n{json.dumps(transcript_preview, indent=2)}"
        if previous_error:
            base += f"\n\nPrevious attempt failed validation:\n{previous_error}\nFix the JSON."
        return base

    def _call_llm(self, prompt: str) -> dict:
        from app.services.llm_provider import make_client, planning_endpoint
        ep = planning_endpoint()
        client = make_client(ep)
        resp = client.chat.completions.create(
            model=ep.model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=2048,
            temperature=settings.planning_temperature,
        )
        raw = resp.choices[0].message.content or "{}"
        raw = raw.strip().strip("```json").strip("```").strip()
        return json.loads(raw)

    def _parse_and_validate(self, data: dict) -> LLMPlan:
        return LLMPlan.model_validate(data)

    def _template_plan(self, video_id: str, scenes: list) -> LLMPlan:
        """Fallback plan when no LLM is configured: keep all non-static scenes."""
        segments = []
        kept_order = 0
        for sc in scenes:
            flags = sc.quality_flags or {}
            is_bad = flags.get("static") or flags.get("blurry")
            action = EditSegmentAction.CUT if is_bad else EditSegmentAction.KEEP
            seg = LLMPlanSegment(
                scene_id=sc.id,
                action=action,
                reason="Auto-generated by template" if not is_bad else "Filtered: static/blurry",
                caption=f"Scene {sc.scene_number}" if not is_bad else "",
                order=kept_order if not is_bad else 0,
            )
            if not is_bad:
                kept_order += 1
            segments.append(seg)
        return LLMPlan(segments=segments)

    def generate_plan(self, video_id: str, scenes: list, segments: list, timeline_events: list | None = None) -> LLMPlan:
        if not planning_endpoint().configured:
            logger.info(f"No planning LLM configured — using template plan for {video_id}")
            return self._template_plan(video_id, scenes)

        prompt = self._build_prompt(video_id, scenes, segments, timeline_events)
        try:
            raw = self._call_llm(prompt)
            return self._parse_and_validate(raw)
        except (ValidationError, Exception) as first_err:
            logger.warning(f"Planning LLM attempt 1 failed for {video_id}: {first_err}")
            retry_prompt = self._build_prompt(video_id, scenes, segments, timeline_events, str(first_err))
            try:
                raw2 = self._call_llm(retry_prompt)
                return self._parse_and_validate(raw2)
            except Exception as second_err:
                raise PlanningError(
                    f"Planning failed after retry for {video_id}: {second_err}"
                ) from second_err


class _PlanningServiceWithTracker(PlanningService):
    def __init__(self):
        self._last_llm_used = False

    def generate_plan(self, video_id, scenes, segments, timeline_events=None):
        if not planning_endpoint().configured:
            self._last_llm_used = False
        else:
            self._last_llm_used = True
        return super().generate_plan(video_id, scenes, segments, timeline_events)


planning_service = _PlanningServiceWithTracker()

